---
- hosts: slave
  user: ansible
  sudo: yes
  connection: ssh
  tasks:
    - name: install apache for debain
      command: apt-get -y install apache2
      when: ansible_os_family == "Debain"
    - name: install apache for redhat
      command: yum -y install httpd
      when: ansible_os_family == "Redhat"


