---
- hosts: slave
  user: ansible
  sudo: yes
  connection: ssh
  tasks:
    - name: install apache
      yum: pkg=httpd state=latest
    - name: verify service status 
      shell: systemctl status httpd
      register: result
      until: result.stdout.find("active (running)") != -1
      retries: 10
      delay: 10
    - debug: var=result



