---
- hosts: slave
  user: ansible
  sudo: yes
  gather_facts: no
  tasks:
    - name: install httpd
      action: yum name=httpd state=installed
      async: 3
      poll: 3
      notify: restart httpd
  handlers:
    - name: restart httpd
      action: service name=httpd state=restarted

