---
- hosts: slave
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: install httpd server on webserver
      yum: pkg=httpd state=installed

